name: NSE 52W Tracker
on:
  schedule:
    - cron: '30 10 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests pandas beautifulsoup4

      - name: Run Script
        run: |
          python main.py
